Fix Intel Compiler illegal narrowing warnings in amr_loadbalance.cpp
src/mesh/amr_loadbalance.cpp(1023): error #2259: non-pointer conversion
from "long long" to "int" may lose significant bits

Not sure why the compiler did not catch them before, since the same
lines were used in mesh.cpp.