Minor formatting changes to gr_blast.cpp
Commented out unused vars in ProblemGenerator()
Include <cmath> to get sqrt() in std:: namespace
Note: src/pgen/gr_blast.cpp(156): error #15552:
loop was not vectorized with "simd"