Add linear(p) OpenMP SIMD clause to unloading steps in bvals_cc.cpp
After refactoring, the identical snippet of code started failing
pgen_compile.py with --cxx=icpc-debug

due to
src/bvals/cc/bvals_cc.cpp(409): error #15552: loop was not vectorized
with "simd"